### ISSUE TITLE
Ngrok is broken when attaching inspector

### ISSUE THREAD

**Issue by bigorangemachine** [itachiRedhair/alexa-skill-local#3]
When attaching an inspector `NODE_ENV=development alexa-skill-local --inspect-brk 5001`

After logging in with Amazon successfully and attaching the debugger to chrome; the html appears when I visit the provided ngrok url

Title: Failed to complete tunnel connection

Body:
```
The connection to https://abc12398.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:3000.

Make sure that a web service is running on localhost:3000 and that it is a valid address.

The error encountered was: dial tcp [::1]:3000: getsockopt: connection refused
```

**Comment by itachiRedhair** [comment]
Debugger which is started using `--inspect-brk` uses websockets. I  am not sure if chrome debugger can work with that.

Instead you can try it with VSCode. Refer to:  _https://github.com/itachiRedhair/alexa-skill-local#usage_

You can also check last part in this article _https://medium.com/@akshay.milmile/alexa-skill-with-nodejs-part-iii-rapid-development-tools-f98294040431_

**Comment by bigorangemachine** [comment]
Thats not the problem.  I *am* able to see the debugger; but then the ngrok endpoint doesn't work (the outputted URL `https://abc12398.ngrok.io`).

However if I close the debugger ngrok will work again.

**Comment by itachiRedhair** [comment]
Can you post some screenshots regarding the problem?

**Comment by itachiRedhair** [comment]
Can you elaborate why you are visiting ngrok url on chrome? 
You might want to attach chrome debugger on localhost:5001.
Ngrok url is your Alexa endpoint and will be automatically updated on Alexa developer console.

**Comment by bigorangemachine** [comment]
I think I know what it is. I didn't hit resume on the debugger. I had to move onto a different part of my project where I didn't need this level of debugging. I will reopen the issue if I need the inspector again

**Comment by bigorangemachine** [comment]
@itachiRedhair confirmed; when you attach to chrome you need to hit the resume button `--inspect-brk` puts a break point in as soon as you load.

FYI [How to attach in chrome](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27):
